name: FGO Login System 14

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "27 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    
      - name: Gettings files from Repo
        uses: actions/checkout@v2
        
      - name: Install Requeriments
        run: |
          pip install -r Allb.txt
          
      - name: Execute main script 1
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS_14 }}
          authKeys: ${{ secrets.GAME_AUTHKEYS_14 }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS_14 }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK_6 }}
          IDEMPOTENCY_KEY_SIGNATURE_SECRET: ${{ secrets.IDEMPOTENCY_KEY_SIGNATURE_SECRET }}
