name: FGO Login System 4

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "07 22 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    
      - name: Gettings files from Repo
        uses: actions/checkout@v2
        
      - name: Install Requeriments
        run: |
          pip install -r Allb.txt

      - name: Execute main script 1
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS_4 }}
          authKeys: ${{ secrets.GAME_AUTHKEYS_4 }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS_4 }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK_4 }}
          IDEMPOTENCY_KEY_SIGNATURE_SECRET: ${{ secrets.IDEMPOTENCY_KEY_SIGNATURE_SECRET }}
